on:
  push:
    branches:
      - master
name: Deploy vsCode Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: phips28/gh-action-bump-version@v11.0.0
        with:
          skip-tag:  'true'
        env:
          GITHUB_USER: "Matthew Pearon"
          GITHUB_EMAIL: "mpearon@users.noreply.github.com"
      - uses: lannonbr/vsce-action@master
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
