name: Call Public VSCE Build Action

on:
  push:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  call_public_vsce_build_action:
    uses: mpearon/public-workflows/.github/workflows/vsce-extension-BuildPublish.yml@main
    with:
      github_user: ${{ vars.GH_USER }}
      github_email: ${{ vars.GH_EMAIL }}
    secrets:
      VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
